# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour_app', '0009_auto_20181022_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
